spring.application.name=receiver
sever.port=8763
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.rabbitmq.addresses=amqps://eilwbnej:MPzldushpmkdfZRp0UZwXC2c_PouRzEO@seal.lmq.cloudamqp.com/eilwbnej
spring.rabbitmq.username=eilwbnej:eilwbnej
spring.rabbitmq.password=MPzldushpmkdfZRp0UZwXC2c_PouRzEO
spring.main.allow-circular-references=true
