spring.application.name=receiver
spring.rabbitmq.addresses=amqps://eilwbnej:MPzldushpmkdfZRp0UZwXC2c_PouRzEO@seal.lmq.cloudamqp.com/eilwbnej
spring.rabbitmq.username=eilwbnej
spring.rabbitmq.password=MPzldushpmkdfZRp0UZwXC2c_PouRzEO

